set -g default-shell pwsh

set -g mouse on
set -g escape-time 0
set -g renumber-windows on
set -g history-limit 10000

set -g status-left "[#S] "
set -g status-right "%H:%M %d-%b-%y"
set -g status-style "bg=brightblue,fg=black"

bind-key -T prefix T display-popup -E "proj tools"
bind-key -T prefix A display-popup -E "proj ai"
bind-key -T prefix r source-file "~/.psmux.conf" \; display-message "psmux.conf reloaded"
