use crate::config::{Config, ShellKind};
use std::fmt::Write;

const HEADER: &str = "Generated by `environment` - do not edit by hand.";

pub fn generate(config: &Config, shell: ShellKind) -> String {
    match shell {
        ShellKind::Bash => bash(config),
        ShellKind::Powershell => powershell(config),
    }
}

fn bash_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

fn ps_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

fn split_home(path: &str) -> Option<&str> {
    match path.strip_prefix('~') {
        Some(rest) if rest.is_empty() || rest.starts_with(['/', '\\']) => Some(rest),
        _ => None,
    }
}

fn ps_remove_alias(name: &str) -> String {
    let path = ps_quote(&format!("Alias:{name}"));
    format!(
        "if (Get-Alias -Name {} -ErrorAction SilentlyContinue) {{ Remove-Item -LiteralPath {path} -Force }}",
        ps_quote(name)
    )
}

fn indent(body: &str) -> String {
    body.trim()
        .lines()
        .map(|l| if l.trim().is_empty() { String::new() } else { format!("    {l}") })
        .collect::<Vec<_>>()
        .join("\n")
}

fn bash(config: &Config) -> String {
    let shell = ShellKind::Bash;
    let mut out = format!("# {HEADER}\n# Source this file from ~/.bashrc:  source /path/to/env.sh\n");

    let env: Vec<_> = config.env.iter().filter_map(|(k, v)| Some((k, v.for_shell(shell)?))).collect();
    if !env.is_empty() {
        out.push_str("\n# Environment\n");
        for (name, value) in env {
            writeln!(out, "export {name}={}", bash_quote(value)).unwrap();
        }
    }

    let paths: Vec<_> = config.path.iter().filter_map(|p| p.for_shell(shell)).collect();
    if !paths.is_empty() {
        out.push_str("\n# PATH\n");
        for path in paths.iter().rev() {
            let quoted = match split_home(path) {
                Some(rest) => format!("\"$HOME\"{}", bash_quote(rest)),
                None => bash_quote(path),
            };
            writeln!(
                out,
                "case \":$PATH:\" in *:{quoted}:*) ;; *) export PATH={quoted}\":$PATH\" ;; esac"
            )
            .unwrap();
        }
    }

    let aliases: Vec<_> = config.aliases.iter().filter_map(|(k, v)| Some((k, v.for_shell(shell)?))).collect();
    if !aliases.is_empty() {
        out.push_str("\n# Aliases\n");
        for (name, command) in aliases {
            writeln!(out, "alias {name}={}", bash_quote(command)).unwrap();
        }
    }

    let functions: Vec<_> = config.functions.iter().filter_map(|(k, v)| Some((k, v.for_shell(shell)?))).collect();
    if !functions.is_empty() {
        out.push_str("\n# Functions\n");
        for (name, body) in functions {
            writeln!(out, "unalias {name} 2>/dev/null\n{name}() {{\n{}\n}}", indent(body)).unwrap();
        }
    }

    out
}

fn powershell(config: &Config) -> String {
    let shell = ShellKind::Powershell;
    let mut out = format!("# {HEADER}\n# Dot-source this file from $PROFILE:  . /path/to/env.ps1\n");

    let env: Vec<_> = config.env.iter().filter_map(|(k, v)| Some((k, v.for_shell(shell)?))).collect();
    if !env.is_empty() {
        out.push_str("\n# Environment\n");
        for (name, value) in env {
            writeln!(out, "$env:{name} = {}", ps_quote(value)).unwrap();
        }
    }

    let paths: Vec<_> = config.path.iter().filter_map(|p| p.for_shell(shell)).collect();
    if !paths.is_empty() {
        out.push_str("\n# PATH\n");
        out.push_str("$__envPaths = @(\n");
        for path in &paths {
            let expr = match split_home(path) {
                Some("") => "$HOME".to_string(),
                Some(rest) => {
                    let segments: Vec<_> =
                        rest.split(['/', '\\']).filter(|s| !s.is_empty()).map(ps_quote).collect();
                    format!("[IO.Path]::Combine($HOME, {})", segments.join(", "))
                }
                None => ps_quote(path),
            };
            writeln!(out, "    {expr}").unwrap();
        }
        out.push_str(
            "\
)
$__envCurrent = $env:PATH -split [IO.Path]::PathSeparator
[array]::Reverse($__envPaths)
foreach ($__p in $__envPaths) {
    if ($__envCurrent -notcontains $__p) {
        $env:PATH = $__p + [IO.Path]::PathSeparator + $env:PATH
    }
}
Remove-Variable __envPaths, __envCurrent, __p -ErrorAction SilentlyContinue
",
        );
    }

    let aliases: Vec<_> = config.aliases.iter().filter_map(|(k, v)| Some((k, v.for_shell(shell)?))).collect();
    if !aliases.is_empty() {
        out.push_str("\n# Aliases\n");
        for (name, command) in aliases {
            writeln!(out, "{}\nfunction global:{name} {{ {command} @args }}", ps_remove_alias(name)).unwrap();
        }
    }

    let functions: Vec<_> = config.functions.iter().filter_map(|(k, v)| Some((k, v.for_shell(shell)?))).collect();
    if !functions.is_empty() {
        out.push_str("\n# Functions\n");
        for (name, body) in functions {
            writeln!(
                out,
                "{}\nfunction global:{name} {{\n    $1, $2, $3, $4, $5, $6, $7, $8, $9 = $args\n{}\n}}",
                ps_remove_alias(name),
                indent(&body.replace("2>/dev/null", "2>$null"))
            )
            .unwrap();
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg(s: &str) -> Config {
        Config::parse(s).unwrap()
    }

    #[test]
    fn quoting() {
        assert_eq!(bash_quote("it's"), r"'it'\''s'");
        assert_eq!(ps_quote("it's"), "'it''s'");
    }

    #[test]
    fn aliases_both_shells() {
        let c = cfg("[aliases]\ngs = \"git status\"\n");
        assert!(generate(&c, ShellKind::Bash).contains("alias gs='git status'"));
        assert!(generate(&c, ShellKind::Powershell).contains("function global:gs { git status @args }"));
    }

    #[test]
    fn per_shell_values_skip_missing() {
        let c = cfg("[aliases]\nll = { bash = \"ls -la\" }\n");
        assert!(generate(&c, ShellKind::Bash).contains("alias ll='ls -la'"));
        assert!(!generate(&c, ShellKind::Powershell).contains("ll"));
    }

    #[test]
    fn env_and_home_paths() {
        let c = cfg("path = [\"~/bin\"]\n[env]\nEDITOR = \"nvim\"\n");
        let b = generate(&c, ShellKind::Bash);
        assert!(b.contains("export EDITOR='nvim'"));
        assert!(b.contains("\"$HOME\"'/bin'"));
        let p = generate(&c, ShellKind::Powershell);
        assert!(p.contains("$env:EDITOR = 'nvim'"));
        assert!(p.contains("[IO.Path]::Combine($HOME, 'bin')"));
    }

    #[test]
    fn rejects_bad_names() {
        assert!(Config::parse("[env]\n\"1BAD\" = \"x\"\n").is_err());
        assert!(Config::parse("[aliases]\n\"a b\" = \"x\"\n").is_err());
        assert!(Config::parse("[aliases]\nx = \"a\"\n[functions]\nx = \"b\"\n").is_err());
    }
}
